apiVersion: apps/v1
kind: Deployment
metadata:
  name: medure-deployment
  labels:
    app: medure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medure
  template:
    metadata:
      labels:
        app: medure
    spec:
      containers:
      - name: medure-container
        image: yourdockerhubusername/medure:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: medure-service
spec:
  type: NodePort
  selector:
    app: medure
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090
